### ISSUE TITLE
[Question] How does paraspec work with transactional examples?

### ISSUE THREAD

**Issue by Epigene** [paraspec/paraspec#17]
Hi!

I am using DatabaseCleaner with the transactional directive and am getting the feeling that paraspec does not play well with this. Plain RSpec run takes 60s, a paraspec run on a single thread takes 5 minutes. More paraspec threads result in failures.

I am getting the feeling that tests ignore database cleaner and are writing to DB.
Would I have better luck with `config.use_transactional_examples = true`?

Using v0.0.2

**Comment by p-mongo** [comment]
Paraspec does have overhead, which is especially noticeable when test suite has many small tests as each test must be individually dispatched. I have ideas for how to reduce the overhead but that is more of a long term project.

When running with concurrency more than 1, did you set up a separate database for each worker?
